### ISSUE TITLE
PartyManager Crash

### ISSUE THREAD

**Issue by wreardan** [jaltekruse/WhatEverYouWantMinecraft#19]
[23:21:18] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException
    at emd24.rpgmod.party.PartyManagerServer.removePlayerFromParty(PartyManagerServer.java:75) ~[PartyManagerServer.class:?]
    at emd24.rpgmod.party.PartyManagerServer.removePlayerFromGame(PartyManagerServer.java:100) ~[PartyManagerServer.class:?]
    at emd24.rpgmod.EventHookContainer.onPlayerLogout(EventHookContainer.java:485) ~[EventHookContainer.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_14_EventHookContainer_onPlayerLogout_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:469) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.playerLoggedOut(ServerConfigurationManager.java:309) ~[ServerConfigurationManager.class:?]
    at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:673) ~[NetHandlerPlayServer.class:?]
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:183) ~[NetworkSystem.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:339) ~[DedicatedServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:650) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:528) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:787) [MinecraftServer$2.class:?]

**Comment by katamaritaco** [comment]
Has this happened since? If not, I would suggest we close it, since there aren't any reproducible steps :3

**Comment by wreardan** [comment]
I believe that I fixed this issue with a Null check.  Closing.
